# default 프로필 -> 개발모드로 사용
spring:
  # thymeleaf 캐시 사용 X로 실시간 reload
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/ # 리눅스용
    prefix: file:src/main/resources/templates/

  # H2 DB -> 메모리 DB 사용위해 임시로 주석
#  datasource:
##    url: jdbc:h2:tcp://localhost/~/secret-art-typing-gallery/secret
#    url: jdbc:h2:tcp://localhost/~/secret-art-typing-gallery/secret;MODE=MySQL;
#    username: sa
#    password:
#      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # DB 초기화 사용 -> 메모리 DB 사용할 거면 당근 초기화는 필수지 (테이블 생성 때매)
#      ddl-auto: none # DB 초기화 사용 X
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  # 메시지 - thymeleaf 연동
  messages:
    basename: messages

server:
  port: 8080
#  address: 223.39.212.163
  servlet:
    session:
      timeout: 30m # session timeout 30min

  # gzip 압축
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 2048

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

my:
  datasource:
    imgPath: C:/images-spring/

logging:
  level:
    com.dau.secretarttypinggallery.controller: debug # 컨트롤러에서만 로그확인
---
# prod 프로필 -> 배포모드로 사용
spring:
  config:
    activate:
      on-profile: prod

  # thymeleaf 캐시 사용!!
  thymeleaf:
    cache: true
    prefix: classpath:/templates/ # 리눅스용

  # MYSQL DB
  datasource:
    url: jdbc:mysql://localhost:3306/secret?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: secretUser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 사용 X
#      ddl-auto: create # DB 초기화 사용

  # 메시지 - thymeleaf 연동
  messages:
    basename: messages

server:
  port: 8080
  servlet:
    session:
      timeout: 30m # session timeout 30min

  # gzip 압축
  compress`ion:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 2048

my:
  datasource:
    imgPath: /var/www/images-spring/

logging:
  level:
    com.dau.secretarttypinggallery.controller: info # 배포는 기본값(info) 사용