# default 프로필 -> 개발모드로 사용
spring:
  # thymeleaf 캐시 사용 X로 실시간 reload
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # H2 DB
  datasource:
    url: jdbc:h2:tcp://localhost/~/secret-art-typing-gallery/secret
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # DB 초기화 사용
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

server:
  port: 8080
#  address: 223.39.212.163
  servlet:
    session:
      timeout: 30m # session timeout 30min

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
#  //            String filePath = "C:/images-spring/"+fileName+".jpeg";
#  String filePath = "/var/www/images-spring/"+fileName+".jpeg";
my:
  datasource:
    imgPath: C:/images-spring/

---
# prod 프로필 -> 배포모드로 사용
spring:
  config:
    activate:
      on-profile: prod
    # MYSQL DB
  datasource:
    url: jdbc:mysql://localhost:3306/secret?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: secretUser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 사용 X

server:
  port: 8080
  servlet:
    session:
      timeout: 30m # session timeout 30min